// ============================================================================
// SALARYPULSE — INITIAL DATA & DEFAULT CONFIGURATION
// Default profile: ₹15,000 / month, Mon-Sat (8h/day), 60m Lunch, Monthly Threshold OT
// ============================================================================

import { 
  AttendanceDay, 
  Holiday, 
  SalaryConfig, 
  User, 
  WorkSchedule 
} from '../types';
import { getDemoEmployeeAttendanceDays } from '../data/employeeDemoPunches';
import { SEPTEMBER_EXTENDED_ATTENDANCE_DAYS } from '../data/septemberExtendedAttendance';

export const INITIAL_USER: User = {
  id: 'EMP-2026-884',
  name: 'Amit Kiran',
  email: 'karamitkiran@gmail.com',
  role: 'Senior Operations Associate',
  department: 'Production & Logistics',
  joiningDate: '2025-01-15',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const INITIAL_SALARY_CONFIG: SalaryConfig = {
  id: 'salary-cfg-v1',
  schemaVersion: 2,
  monthlyBaseSalary: 15000,
  currency: 'INR',
  calculationBasis: 'monthly_scheduled_hours', // Standard 26 Working Days: ₹15,000 ÷ 26 = ₹576.92/day (8h), ₹72.12/hr
  
  // Overtime defaults
  overtimeMethod: 'daily_threshold',
  overtimeMultiplier: 1.0,
  overtimeThresholdMinutes: 0,
  weeklyOffWorkRule: 'add_to_monthly_threshold',
  holidayWorkRule: 'holiday_credit_plus_monthly_threshold',

  // Holiday defaults
  defaultPaidHolidayCreditedHours: 8.0,

  // Attendance bonus defaults
  attendanceBonusEnabled: true,
  attendanceBonusAmount: 3000,
  attendanceBonusEligibleDays: 26,
  bonusRequiresApproval: true,
  autoApproveBonusOnEligible: false,

  // Deductions default to empty (no automatic statutory deduction)
  deductions: [],

  // Effective date
  effectiveFrom: '2026-08-01',
};

export const INITIAL_SCHEDULE: WorkSchedule = {
  id: 'schedule-standard-mon-sat',
  name: 'Standard Mon-Sat Shift',
  workingDays: [1, 2, 3, 4, 5, 6], // Monday through Saturday (0 = Sunday is OFF)
  officeStartTime: '09:00',
  officeEndTime: '18:00',
  requiredActiveHoursPerDay: 8.0, // 8 hours active work required
  breakRules: [
    {
      id: 'brk-lunch',
      name: 'Lunch Break',
      durationMinutes: 60,
      isPaid: false,
      isEnabled: true,
      type: 'lunch',
    },
    {
      id: 'brk-tea',
      name: 'Evening Tea Break',
      durationMinutes: 15,
      isPaid: true,
      isEnabled: true,
      type: 'tea',
    },
  ],
  defaultLunchDurationMinutes: 60,
  defaultTeaBreakDurationMinutes: 15,
};

export const INITIAL_HOLIDAYS: Holiday[] = [
  {
    id: 'hol-1',
    date: '2026-08-15',
    name: 'Independence Day',
    type: 'paid',
    creditedHours: 8.0,
  },
  {
    id: 'hol-2',
    date: '2026-08-27',
    name: 'Raksha Bandhan',
    type: 'paid',
    creditedHours: 8.0,
  },
  {
    id: 'hol-1789498584241',
    date: '2026-09-17',
    name: 'Viswakarma Puja',
    type: 'paid',
    creditedHours: 8.0,
    customAmount: 500,
  },
];

// Helper to construct the full authoritative 82-day attendance records
function buildAllSeededAttendanceDays(): AttendanceDay[] {
  const baseDays = getDemoEmployeeAttendanceDays(8.0);
  const datesMap = new Map<string, AttendanceDay>();
  baseDays.forEach(d => datesMap.set(d.date, d));
  SEPTEMBER_EXTENDED_ATTENDANCE_DAYS.forEach(d => datesMap.set(d.date, d));
  return Array.from(datesMap.values()).sort((a, b) => a.date.localeCompare(b.date));
}

// Official Employee Punch Records (82 days: May 25, 2026 to Sep 16, 2026)
export const INITIAL_ATTENDANCE_DAYS: AttendanceDay[] = buildAllSeededAttendanceDays();

export const INITIAL_SALARY_RECONCILIATION_RECORDS: import('../types').SalaryReconciliationRecord[] = [
  {
    id: 'recon-sal-2026-08',
    month: '2026-08',
    status: 'DISPUTE_RAISED',
    isLocked: false,
    lastUpdated: '2026-08-15T10:30:00Z',
    pulseData: {
      grossSalary: 19384.62,
      basePay: 15000.0,
      overtimePay: 1384.62,
      attendanceBonus: 3000.0,
      performanceBonus: 0,
      specialAllowance: 0,
      totalDeductions: 0,
      itemizedDeductions: [],
      netPay: 19384.62,
      scheduledWorkingDays: 26,
      presentDays: 13,
      otHours: 12.0,
      perDayRate: 576.92,
      perHourRate: 72.12,
      calculationBasis: 'monthly_scheduled_hours',
    },
    officialSlip: {
      isProvided: true,
      slipNumber: 'PAYSLIP-2026-08-1042',
      disbursalDate: '2026-08-31',
      employerName: 'Apex Precision Logistics Ltd.',
      employeeId: 'EMP-2026-884',
      basePay: 15000.0,
      overtimePay: 692.31, // Counted at 1x multiplier instead of 2.0x
      attendanceBonus: 0,   // Omitted / pending HR verification
      performanceBonus: 0,
      specialAllowance: 500.0,
      otherEarnings: 0,
      grossPay: 16192.31,
      deductions: {
        pf: 1800.0,
        pt: 200.0,
        tds: 0,
        esi: 0,
        lop: 0,
        other: 0,
      },
      totalDeductions: 2000.0,
      netSalary: 14192.31,
      reportedWorkDays: 26,
      reportedPresentDays: 13,
      reportedOTHours: 9.6,
      remarks: 'Overtime computed at single rate standard; attendance bonus subject to month-end attendance audit.',
    },
    bankReceipt: {
      isProvided: false,
      amountReceived: 0,
      depositDate: '',
      bankName: 'HDFC Bank',
      accountLast4: '4829',
      transactionRef: '',
      depositStatus: 'PENDING',
      notes: 'Awaiting end-of-month salary disbursement.',
    },
    itemizedDiscrepancies: [
      {
        id: 'disc-ot-diff',
        category: 'OVERTIME',
        title: 'Unpaid / Under-calculated Overtime',
        description: 'SalaryPulse logged 12.0 OT hours (₹1,384.62 @ 2.0x) vs Official OT of ₹692.31.',
        pulseAmount: 1384.62,
        officialAmount: 692.31,
        variance: -692.31,
        severity: 'CRITICAL',
        driver: 'HR payroll applied a 1.0x rate instead of the configured 2.0x overtime multiplier.',
        impactNote: 'Net OT underpayment of ₹692.31.',
        userResolution: 'DISPUTED_WITH_HR',
      },
      {
        id: 'disc-bonus-diff',
        category: 'ATTENDANCE_BONUS',
        title: 'Attendance Bonus Omitted in Draft Slip',
        description: 'SalaryPulse projected attendance bonus of ₹3,000.00 vs Official HR Slip amount of ₹0.00.',
        pulseAmount: 3000.0,
        officialAmount: 0,
        variance: -3000.0,
        severity: 'CRITICAL',
        driver: 'HR system attendance threshold pending month-end closing approval.',
        impactNote: 'Bonus variance of -₹3,000.00.',
        userResolution: 'DISPUTED_WITH_HR',
      },
      {
        id: 'disc-ded-pf',
        category: 'PF_STATUTORY',
        title: 'Provident Fund (PF) Statutory Deduction',
        description: 'Official slip deducted ₹1,800.00 towards employee PF (EPFO).',
        pulseAmount: 0,
        officialAmount: 1800.0,
        variance: -1800.0,
        severity: 'INFO',
        driver: 'Mandatory statutory retirement savings contribution (12% of basic).',
        impactNote: 'Statutory compliance deduction.',
        userResolution: 'ACCEPTED_OFFICIAL',
      },
      {
        id: 'disc-ded-pt',
        category: 'PT_TAX',
        title: 'Professional Tax (PT)',
        description: 'State Government Professional Tax of ₹200.00 deducted on official slip.',
        pulseAmount: 0,
        officialAmount: 200.0,
        variance: -200.0,
        severity: 'INFO',
        driver: 'State statutory professional tax levy.',
        impactNote: 'Mandatory state deduction.',
        userResolution: 'ACCEPTED_OFFICIAL',
      },
    ],
    forensicSummary: {
      headline: 'Net Take-Home Discrepancy: -₹5,192.31 vs Projected Accrual',
      netVariance: -5192.31,
      bankVariance: 0,
      totalDiscrepanciesCount: 4,
      criticalCount: 2,
      warningCount: 0,
      explanationSteps: [
        'Official take-home (₹14,192.31) is ₹5,192.31 lower than SalaryPulse projected take-home (₹19,384.62).',
        '• Overtime Variance: -₹692.31 (HR computed OT at 1.0x rate instead of contractual 2.0x).',
        '• Attendance Bonus: -₹3,000.00 (Pending final attendance reconciliation by HR).',
        '• Statutory Deductions: -₹2,000.00 (PF: ₹1,800.00, PT: ₹200.00).',
        '• Bank Deposit: Pending actual bank credit entry at month end.',
      ],
      keyFinancialDrivers: [
        { label: 'Attendance Bonus Uncredited', amount: -3000.0, direction: 'NEGATIVE' },
        { label: 'Statutory PF & PT Deductions', amount: -2000.0, direction: 'NEGATIVE' },
        { label: 'Underpaid Overtime Multiplier', amount: -692.31, direction: 'NEGATIVE' },
        { label: 'Special Allowance Credited', amount: 500.0, direction: 'POSITIVE' },
      ],
      actionRecommendations: [
        'Submit the 2.0x overtime multiplier agreement to HR to claim ₹692.31 in unpaid overtime.',
        'Request HR to credit the ₹3,000.00 attendance bonus once the 26-day attendance threshold is reached.',
      ],
      suggestedHRDisputeTemplate: 'To: Payroll / HR\nSubject: Overtime Multiplier & Attendance Incentive Review - Aug 2026',
    },
    disputeNotes: 'Raised query with Payroll Specialist regarding 2.0x overtime multiplier on Saturday shifts and attendance bonus eligibility.',
    disputeTicketRef: 'PAY-DISP-2026-8841',
    disputeStatus: 'DRAFTED',
  },
  {
    id: 'recon-sal-2026-07',
    month: '2026-07',
    status: 'LOCKED_FINAL',
    isLocked: true,
    lockedAt: '2026-08-05T09:00:00Z',
    lockedBy: 'Amit Kiran',
    lastUpdated: '2026-08-05T09:00:00Z',
    pulseData: {
      grossSalary: 19777.78,
      basePay: 15000.0,
      overtimePay: 1777.78,
      attendanceBonus: 3000.0,
      performanceBonus: 0,
      specialAllowance: 0,
      totalDeductions: 0,
      itemizedDeductions: [],
      netPay: 19777.78,
      scheduledWorkingDays: 27,
      presentDays: 27,
      otHours: 16.0,
      perDayRate: 555.56,
      perHourRate: 69.44,
      calculationBasis: 'monthly_scheduled_hours',
    },
    officialSlip: {
      isProvided: true,
      slipNumber: 'PAYSLIP-2026-07-0941',
      disbursalDate: '2026-07-31',
      employerName: 'Apex Precision Logistics Ltd.',
      employeeId: 'EMP-2026-884',
      basePay: 15000.0,
      overtimePay: 888.89, // Paid at 1.0x
      attendanceBonus: 3000.0,
      performanceBonus: 0,
      specialAllowance: 0,
      otherEarnings: 0,
      grossPay: 18888.89,
      deductions: {
        pf: 1800.0,
        pt: 200.0,
        tds: 500.0,
        esi: 0,
        lop: 0,
        other: 0,
      },
      totalDeductions: 2500.0,
      netSalary: 16388.89,
      reportedWorkDays: 27,
      reportedPresentDays: 27,
      reportedOTHours: 12.8,
      remarks: 'July payroll closed. Attendance bonus credited in full.',
    },
    bankReceipt: {
      isProvided: true,
      amountReceived: 16388.89,
      depositDate: '2026-08-01',
      bankName: 'HDFC Bank',
      accountLast4: '4829',
      transactionRef: 'NEFT/HDFC/SAL0726982',
      depositStatus: 'RECEIVED',
      notes: 'Direct salary transfer received in full on 1st August.',
    },
    itemizedDiscrepancies: [
      {
        id: 'disc-bank-match-07',
        category: 'BANK_TRANSFER',
        title: 'Bank Deposit Matches Official Net Exactly',
        description: 'Bank credited ₹16,388.89 on 2026-08-01 (Ref: NEFT/HDFC/SAL0726982), matching the official slip net salary.',
        pulseAmount: 16388.89,
        officialAmount: 16388.89,
        variance: 0,
        severity: 'MATCH',
        driver: 'Complete and accurate electronic salary remittance.',
        impactNote: 'Bank deposit verified.',
        userResolution: 'RECONCILED',
      },
    ],
    forensicSummary: {
      headline: 'July 2026 Reconciled & Locked',
      netVariance: -3388.89,
      bankVariance: 0,
      totalDiscrepanciesCount: 1,
      criticalCount: 0,
      warningCount: 0,
      explanationSteps: [
        'Official take-home (₹16,388.89) was credited directly to HDFC Bank account ending in 4829 on 1st August.',
        '• Statutory Deductions: -₹2,500.00 (PF ₹1,800, PT ₹200, TDS ₹500).',
        '• Full Attendance Bonus of ₹3,000.00 was approved and paid.',
        '• Month finalized and permanently locked.',
      ],
      keyFinancialDrivers: [
        { label: 'Statutory Deductions (PF/PT/TDS)', amount: -2500.0, direction: 'NEGATIVE' },
        { label: 'Overtime 1.0x Rate Gap', amount: -888.89, direction: 'NEGATIVE' },
        { label: 'Full Attendance Bonus Paid', amount: 3000.0, direction: 'POSITIVE' },
      ],
      actionRecommendations: ['Record is locked for audit.'],
      suggestedHRDisputeTemplate: '',
    },
    disputeNotes: 'OT 1.0x vs 2.0x variance resolved: HR confirmed overtime policy amendment starting August.',
    disputeStatus: 'RESOLVED_ACCEPTED',
  },
  {
    id: 'recon-sal-2026-06',
    month: '2026-06',
    status: 'LOCKED_FINAL',
    isLocked: true,
    lockedAt: '2026-07-03T11:00:00Z',
    lockedBy: 'Amit Kiran',
    lastUpdated: '2026-07-03T11:00:00Z',
    pulseData: {
      grossSalary: 18923.08,
      basePay: 15000.0,
      overtimePay: 923.08,
      attendanceBonus: 3000.0,
      performanceBonus: 0,
      specialAllowance: 0,
      totalDeductions: 0,
      itemizedDeductions: [],
      netPay: 18923.08,
      scheduledWorkingDays: 26,
      presentDays: 26,
      otHours: 8.0,
      perDayRate: 576.92,
      perHourRate: 72.12,
      calculationBasis: 'monthly_scheduled_hours',
    },
    officialSlip: {
      isProvided: true,
      slipNumber: 'PAYSLIP-2026-06-0812',
      disbursalDate: '2026-06-30',
      employerName: 'Apex Precision Logistics Ltd.',
      employeeId: 'EMP-2026-884',
      basePay: 15000.0,
      overtimePay: 923.08,
      attendanceBonus: 3000.0,
      performanceBonus: 0,
      specialAllowance: 0,
      otherEarnings: 0,
      grossPay: 18923.08,
      deductions: {
        pf: 1800.0,
        pt: 200.0,
        tds: 0,
        esi: 0,
        lop: 0,
        other: 0,
      },
      totalDeductions: 2000.0,
      netSalary: 16923.08,
      reportedWorkDays: 26,
      reportedPresentDays: 26,
      reportedOTHours: 8.0,
      remarks: 'June payroll processed without discrepancies.',
    },
    bankReceipt: {
      isProvided: true,
      amountReceived: 16923.08,
      depositDate: '2026-07-01',
      bankName: 'HDFC Bank',
      accountLast4: '4829',
      transactionRef: 'NEFT/HDFC/SAL0626114',
      depositStatus: 'RECEIVED',
      notes: 'Full remittance verified.',
    },
    itemizedDiscrepancies: [
      {
        id: 'disc-base-match-06',
        category: 'BASE_PAY',
        title: 'Base Pay Matches Exactly',
        description: 'Both SalaryPulse and Official HR Slip record base salary of ₹15,000.00.',
        pulseAmount: 15000.0,
        officialAmount: 15000.0,
        variance: 0,
        severity: 'MATCH',
        driver: 'Scheduled working days and base salary rate match official records.',
        impactNote: 'Zero variance.',
        userResolution: 'RECONCILED',
      },
      {
        id: 'disc-bank-match-06',
        category: 'BANK_TRANSFER',
        title: 'Bank Deposit Matches Official Net Exactly',
        description: 'Bank credited ₹16,923.08 on 2026-07-01, perfectly matching official net pay.',
        pulseAmount: 16923.08,
        officialAmount: 16923.08,
        variance: 0,
        severity: 'MATCH',
        driver: 'Complete electronic remittance.',
        impactNote: 'Bank deposit verified.',
        userResolution: 'RECONCILED',
      },
    ],
    forensicSummary: {
      headline: 'June 2026 Perfect Match Reconciled',
      netVariance: -2000.0,
      bankVariance: 0,
      totalDiscrepanciesCount: 2,
      criticalCount: 0,
      warningCount: 0,
      explanationSteps: [
        'June 2026 salary reconciliation completed with zero unexplained discrepancies.',
        '• Take-home after standard PF (₹1,800) and PT (₹200) was ₹16,923.08.',
        '• Deposited to HDFC Bank on July 1st.',
      ],
      keyFinancialDrivers: [
        { label: 'Statutory PF & PT Deductions', amount: -2000.0, direction: 'NEGATIVE' },
      ],
      actionRecommendations: ['Month permanently archived.'],
      suggestedHRDisputeTemplate: '',
    },
  },
];

